[book]
authors = ["Rolly Fordham"]
language = "en"
multilingual = false
src = "src"
title = "Menagerie"
description = "My notes on various technical topics"

[build]
create-missing = true

[output.html]
mathjax-support = true

[output.html.search]
limit-results = 15
